@startuml
Main "1" *-- "many" BankAccount : has
Main "1" *-- "1" UI : has
Main : static ArrayList<BankAccount> accounts
Main : readGameData()


BankAccount : float balance
BankAccount : String owner
BankAccount : int stalkingCounter

@enduml

