@startuml
Main "1" *-- "many" BankAccount : has
Main "1" *-- "1" UI : has
Main : static ArrayList<BankAccount> accounts

class Main {
~ {static} ArrayList<BankAccount> accounts
+ {static} void main(String[])
- {static} void readGameData()
- {static} void showMenu()
- {static} void printAccounts()
}
class BankAccount {
- float balance
- String owner
- int stalkingCounter
+ void doTransaction(float)
+ String toString()
+ float getBalance()
+ String getOwner()
}
class UI {
~ {static} int MAX
+ void createAccounts()
+ String getUserInput(String)
+ void manageAccount()
}
@enduml
